---
name: Delivery

on:
  push:
    branches:
      - main
    paths:
      - 'image/**'

env:
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/antlr4

jobs:
  publish-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push (version)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: $DOCKER_IMAGE:4.13.1
      - name: Build and push (latest)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: $DOCKER_IMAGE:latest
